---
Naive Bayes
---
```{r}
#install.packages("e1071")
library(e1071)
```
Dados de Crédito de Banco 
```{r}
credito = read.csv("Credit.csv")
head(credito)
dim(credito)
```
Transformamos a classe em fator
```{r}
credito$class = as.factor(credito$class)
```
Separamos dados de treino e teste
dividindo as amostras em 70% para treino e 30% para teste 
```{r}
amostra = sample(2,1000,replace=T, prob=c(0.7,0.3))
amostra
creditotreino = credito[amostra==1,]
creditoteste = credito[amostra==2,]
```
Dimensões dos conjuntos
class dependente e .(todas as outras variaveis como idependente)
```{r}
dim(creditotreino)
dim(creditoteste)
```
Criamos o modelo
```{r}
modelo <- naiveBayes(class ~., creditotreino)
modelo
```
Previsão
```{r}
predicao <- predict(modelo,creditoteste)
predicao
```
Matriz de Confusão
```{r}
confusao = table(creditoteste$class,predicao)
confusao
taxaacerto = (confusao[1] + confusao[4]) / sum(confusao)
taxaerro = (confusao[2] + confusao[3]) / sum(confusao)
taxaacerto
taxaerro
```


```{r}
```


